// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zdztwacnpmhonzjjxskm.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpkenR3YWNucG1ob256amp4c2ttIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM5Mjg4NDYsImV4cCI6MjA2OTUwNDg0Nn0.vYkxbtnqVpsvL_9jS7QYTHNoUIZFmGZsV6eOSpeKjpo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});